# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.physical_resource import PhysicalResource


class PhysicalResourceDeleteEventPayload(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PhysicalResourceDeleteEventPayload - a model defined in OpenAPI

        physical_resource: The physical_resource of this PhysicalResourceDeleteEventPayload [Optional].
    """

    physical_resource: Optional[PhysicalResource] = Field(alias="physicalResource", default=None)

PhysicalResourceDeleteEventPayload.update_forward_refs()
