# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PlaceRef(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PlaceRef - a model defined in OpenAPI

        id: The id of this PlaceRef.
        href: The href of this PlaceRef [Optional].
        name: The name of this PlaceRef [Optional].
        base_type: The base_type of this PlaceRef [Optional].
        schema_location: The schema_location of this PlaceRef [Optional].
        type: The type of this PlaceRef [Optional].
        referred_type: The referred_type of this PlaceRef [Optional].
    """

    id: str = Field(alias="id")
    href: Optional[str] = Field(alias="href", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    base_type: Optional[str] = Field(alias="@baseType", default=None)
    schema_location: Optional[AnyUrl] = Field(alias="@schemaLocation", default=None)
    type: Optional[str] = Field(alias="@type", default=None)
    referred_type: Optional[str] = Field(alias="@referredType", default=None)

PlaceRef.update_forward_refs()
