# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Place(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Place - a model defined in OpenAPI

        id: The id of this Place.
        href: The href of this Place.
        name: The name of this Place [Optional].
        role: The role of this Place.
        base_type: The base_type of this Place [Optional].
        schema_location: The schema_location of this Place [Optional].
        type: The type of this Place [Optional].
    """

    id: str = Field(alias="id")
    href: str = Field(alias="href")
    name: Optional[str] = Field(alias="name", default=None)
    role: str = Field(alias="role")
    base_type: Optional[str] = Field(alias="@baseType", default=None)
    schema_location: Optional[AnyUrl] = Field(alias="@schemaLocation", default=None)
    type: Optional[str] = Field(alias="@type", default=None)

Place.update_forward_refs()
