# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.resource_attribute_value_change_event_payload import ResourceAttributeValueChangeEventPayload


class ResourceAttributeValueChangeEvent(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceAttributeValueChangeEvent - a model defined in OpenAPI

        event_id: The event_id of this ResourceAttributeValueChangeEvent [Optional].
        event_time: The event_time of this ResourceAttributeValueChangeEvent [Optional].
        event_type: The event_type of this ResourceAttributeValueChangeEvent [Optional].
        correlation_id: The correlation_id of this ResourceAttributeValueChangeEvent [Optional].
        domain: The domain of this ResourceAttributeValueChangeEvent [Optional].
        title: The title of this ResourceAttributeValueChangeEvent [Optional].
        description: The description of this ResourceAttributeValueChangeEvent [Optional].
        priority: The priority of this ResourceAttributeValueChangeEvent [Optional].
        time_ocurred: The time_ocurred of this ResourceAttributeValueChangeEvent [Optional].
        field_path: The field_path of this ResourceAttributeValueChangeEvent [Optional].
        event: The event of this ResourceAttributeValueChangeEvent [Optional].
    """

    event_id: Optional[str] = Field(alias="eventId", default=None)
    event_time: Optional[datetime] = Field(alias="eventTime", default=None)
    event_type: Optional[str] = Field(alias="eventType", default=None)
    correlation_id: Optional[str] = Field(alias="correlationId", default=None)
    domain: Optional[str] = Field(alias="domain", default=None)
    title: Optional[str] = Field(alias="title", default=None)
    description: Optional[str] = Field(alias="description", default=None)
    priority: Optional[str] = Field(alias="priority", default=None)
    time_ocurred: Optional[datetime] = Field(alias="timeOcurred", default=None)
    field_path: Optional[str] = Field(alias="fieldPath", default=None)
    event: Optional[ResourceAttributeValueChangeEventPayload] = Field(alias="event", default=None)

ResourceAttributeValueChangeEvent.update_forward_refs()
