# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.characteristic import Characteristic


class ResourceRelationship(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceRelationship - a model defined in OpenAPI

        id: The id of this ResourceRelationship [Optional].
        href: The href of this ResourceRelationship [Optional].
        relationship_type: The relationship_type of this ResourceRelationship [Optional].
        resource_relationship_characteristic: The resource_relationship_characteristic of this ResourceRelationship [Optional].
        base_type: The base_type of this ResourceRelationship [Optional].
        schema_location: The schema_location of this ResourceRelationship [Optional].
        type: The type of this ResourceRelationship [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    href: Optional[str] = Field(alias="href", default=None)
    relationship_type: Optional[str] = Field(alias="relationshipType", default=None)
    resource_relationship_characteristic: Optional[List[Characteristic]] = Field(alias="resourceRelationshipCharacteristic", default=None)
    base_type: Optional[str] = Field(alias="@baseType", default=None)
    schema_location: Optional[AnyUrl] = Field(alias="@schemaLocation", default=None)
    type: Optional[str] = Field(alias="@type", default=None)

ResourceRelationship.update_forward_refs()
