# coding: utf-8

"""
    Resource Inventory Management

    This is Swagger UI environment generated for the TMF Resource Inventory Management specification

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.events_subscription_api import router as EventsSubscriptionApiRouter
from openapi_server.apis.logical_resource_api import router as LogicalResourceApiRouter
from openapi_server.apis.notification_listeners_client_side_api import router as NotificationListenersClientSideApiRouter
from openapi_server.apis.physical_resource_api import router as PhysicalResourceApiRouter
from openapi_server.apis.resource_api import router as ResourceApiRouter

from common import agent_logging
from common import agent
from threading import Thread

app = FastAPI(
    title="Resource Inventory Management",
    description="This is Swagger UI environment generated for the TMF Resource Inventory Management specification",
    version="4.0.0",
)

app.include_router(EventsSubscriptionApiRouter)
app.include_router(LogicalResourceApiRouter)
app.include_router(NotificationListenersClientSideApiRouter)
app.include_router(PhysicalResourceApiRouter)
app.include_router(ResourceApiRouter)


myAgent=agent.MyAgent()

@app.on_event("startup")
async def startup_event():
    agent_logging.logger.info("****************************************************") 
    agent_logging.logger.info("*Start up")
    agent_logging.logger.info("*Steps to take:")
    agent_logging.logger.info("*Initialize self (read from text files)")
    agent_logging.logger.info("*Self register")
    agent_logging.logger.info("****Create Resource for self register")
    agent_logging.logger.info("****************************************************") 

    # agent_logging.test()
    # status_t=Thread(target=talk_to_server.status_thread, args=("My Status",))
    # status_t.start()
    myAgent.startSelfRegisterProccess()
    myAgent.talk2server=Thread(target=myAgent.talk_to_server, args=("My Status",))
    #tekan from https://www.geeksforgeeks.org/python-different-ways-to-kill-a-thread
    myAgent.talk2server.daemon=True #This will also kill the trhead when the main program exits 
    myAgent.talk2server.start()
    


@app.on_event("shutdown")
def shutdown_event():
   agent_logging.logger.info("****************************************************") 
   agent_logging.logger.info("Shut down")
   agent_logging.logger.info("Change operationalState ")
   agent_logging.logger.info("****************************************************") 
   myAgent.talk2server.stop()