# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.characteristic_relationship import CharacteristicRelationship


class Characteristic(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Characteristic - a model defined in OpenAPI

        id: The id of this Characteristic [Optional].
        name: The name of this Characteristic.
        value_type: The value_type of this Characteristic [Optional].
        characteristic_relationship: The characteristic_relationship of this Characteristic [Optional].
        value: The value of this Characteristic.
        base_type: The base_type of this Characteristic [Optional].
        schema_location: The schema_location of this Characteristic [Optional].
        type: The type of this Characteristic [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    name: str = Field(alias="name")
    value_type: Optional[str] = Field(alias="valueType", default=None)
    characteristic_relationship: Optional[List[CharacteristicRelationship]] = Field(alias="characteristicRelationship", default=None)
    value: Dict[str, Any] = Field(alias="value")
    base_type: Optional[str] = Field(alias="@baseType", default=None)
    schema_location: Optional[AnyUrl] = Field(alias="@schemaLocation", default=None)
    type: Optional[str] = Field(alias="@type", default=None)

Characteristic.update_forward_refs()
