# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CharacteristicRelationship(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CharacteristicRelationship - a model defined in OpenAPI

        id: The id of this CharacteristicRelationship [Optional].
        relationship_type: The relationship_type of this CharacteristicRelationship [Optional].
        base_type: The base_type of this CharacteristicRelationship [Optional].
        schema_location: The schema_location of this CharacteristicRelationship [Optional].
        type: The type of this CharacteristicRelationship [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    relationship_type: Optional[str] = Field(alias="relationshipType", default=None)
    base_type: Optional[str] = Field(alias="@baseType", default=None)
    schema_location: Optional[AnyUrl] = Field(alias="@schemaLocation", default=None)
    type: Optional[str] = Field(alias="@type", default=None)

CharacteristicRelationship.update_forward_refs()
