# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Error(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Error - a model defined in OpenAPI

        code: The code of this Error.
        reason: The reason of this Error.
        message: The message of this Error [Optional].
        status: The status of this Error [Optional].
        reference_error: The reference_error of this Error [Optional].
        base_type: The base_type of this Error [Optional].
        schema_location: The schema_location of this Error [Optional].
        type: The type of this Error [Optional].
    """

    code: str = Field(alias="code")
    reason: str = Field(alias="reason")
    message: Optional[str] = Field(alias="message", default=None)
    status: Optional[str] = Field(alias="status", default=None)
    reference_error: Optional[AnyUrl] = Field(alias="referenceError", default=None)
    base_type: Optional[str] = Field(alias="@baseType", default=None)
    schema_location: Optional[AnyUrl] = Field(alias="@schemaLocation", default=None)
    type: Optional[str] = Field(alias="@type", default=None)

Error.update_forward_refs()
