# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ResourceSpecificationRef(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceSpecificationRef - a model defined in OpenAPI

        id: The id of this ResourceSpecificationRef.
        href: The href of this ResourceSpecificationRef.
        name: The name of this ResourceSpecificationRef [Optional].
        version: The version of this ResourceSpecificationRef [Optional].
        base_type: The base_type of this ResourceSpecificationRef [Optional].
        schema_location: The schema_location of this ResourceSpecificationRef [Optional].
        type: The type of this ResourceSpecificationRef [Optional].
        referred_type: The referred_type of this ResourceSpecificationRef [Optional].
    """

    id: str = Field(alias="id")
    href: str = Field(alias="href")
    name: Optional[str] = Field(alias="name", default=None)
    version: Optional[str] = Field(alias="version", default=None)
    base_type: Optional[str] = Field(alias="@baseType", default=None)
    schema_location: Optional[AnyUrl] = Field(alias="@schemaLocation", default=None)
    type: Optional[str] = Field(alias="@type", default=None)
    referred_type: Optional[str] = Field(alias="@referredType", default=None)

ResourceSpecificationRef.update_forward_refs()
