# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.resource_state_change_event_payload import ResourceStateChangeEventPayload


class ResourceStateChangeEvent(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceStateChangeEvent - a model defined in OpenAPI

        id: The id of this ResourceStateChangeEvent [Optional].
        href: The href of this ResourceStateChangeEvent [Optional].
        event_id: The event_id of this ResourceStateChangeEvent [Optional].
        event_time: The event_time of this ResourceStateChangeEvent [Optional].
        event_type: The event_type of this ResourceStateChangeEvent [Optional].
        correlation_id: The correlation_id of this ResourceStateChangeEvent [Optional].
        domain: The domain of this ResourceStateChangeEvent [Optional].
        title: The title of this ResourceStateChangeEvent [Optional].
        description: The description of this ResourceStateChangeEvent [Optional].
        priority: The priority of this ResourceStateChangeEvent [Optional].
        time_ocurred: The time_ocurred of this ResourceStateChangeEvent [Optional].
        event: The event of this ResourceStateChangeEvent [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    href: Optional[str] = Field(alias="href", default=None)
    event_id: Optional[str] = Field(alias="eventId", default=None)
    event_time: Optional[datetime] = Field(alias="eventTime", default=None)
    event_type: Optional[str] = Field(alias="eventType", default=None)
    correlation_id: Optional[str] = Field(alias="correlationId", default=None)
    domain: Optional[str] = Field(alias="domain", default=None)
    title: Optional[str] = Field(alias="title", default=None)
    description: Optional[str] = Field(alias="description", default=None)
    priority: Optional[str] = Field(alias="priority", default=None)
    time_ocurred: Optional[datetime] = Field(alias="timeOcurred", default=None)
    event: Optional[ResourceStateChangeEventPayload] = Field(alias="event", default=None)

ResourceStateChangeEvent.update_forward_refs()
