# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.attachment_ref_or_value import AttachmentRefOrValue
from openapi_server.models.characteristic import Characteristic
from openapi_server.models.feature import Feature
from openapi_server.models.note import Note
from openapi_server.models.related_party import RelatedParty
from openapi_server.models.related_place_ref_or_value import RelatedPlaceRefOrValue
from openapi_server.models.resource_administrative_state_type import ResourceAdministrativeStateType
from openapi_server.models.resource_operational_state_type import ResourceOperationalStateType
from openapi_server.models.resource_relationship import ResourceRelationship
from openapi_server.models.resource_specification_ref import ResourceSpecificationRef
from openapi_server.models.resource_status_type import ResourceStatusType
from openapi_server.models.resource_usage_state_type import ResourceUsageStateType


class ResourceUpdate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceUpdate - a model defined in OpenAPI

        category: The category of this ResourceUpdate [Optional].
        description: The description of this ResourceUpdate [Optional].
        end_operating_date: The end_operating_date of this ResourceUpdate [Optional].
        name: The name of this ResourceUpdate [Optional].
        resource_version: The resource_version of this ResourceUpdate [Optional].
        start_operating_date: The start_operating_date of this ResourceUpdate [Optional].
        activation_feature: The activation_feature of this Resource [Optional].
        administrative_state: The administrative_state of this ResourceUpdate [Optional].
        attachment: The attachment of this ResourceUpdate [Optional].
        note: The note of this ResourceUpdate [Optional].
        operational_state: The operational_state of this ResourceUpdate [Optional].
        place: The place of this ResourceUpdate [Optional].
        related_party: The related_party of this ResourceUpdate [Optional].
        resource_characteristic: The resource_characteristic of this ResourceUpdate [Optional].
        resource_relationship: The resource_relationship of this ResourceUpdate [Optional].
        resource_specification: The resource_specification of this ResourceUpdate [Optional].
        resource_status: The resource_status of this ResourceUpdate [Optional].
        usage_state: The usage_state of this ResourceUpdate [Optional].
        base_type: The base_type of this ResourceUpdate [Optional].
        schema_location: The schema_location of this ResourceUpdate [Optional].
        type: The type of this ResourceUpdate [Optional].
    """

    category: Optional[str] = Field(alias="category", default=None)
    description: Optional[str] = Field(alias="description", default=None)
    end_operating_date: Optional[datetime] = Field(alias="endOperatingDate", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    resource_version: Optional[str] = Field(alias="resourceVersion", default=None)
    start_operating_date: Optional[datetime] = Field(alias="startOperatingDate", default=None)
    administrative_state: Optional[ResourceAdministrativeStateType] = Field(alias="administrativeState", default=None)
    attachment: Optional[List[AttachmentRefOrValue]] = Field(alias="attachment", default=None)
    note: Optional[List[Note]] = Field(alias="note", default=None)
    operational_state: Optional[ResourceOperationalStateType] = Field(alias="operationalState", default=None)
    activation_feature: Optional[List[Feature]] = None
    place: Optional[RelatedPlaceRefOrValue] = Field(alias="place", default=None)
    related_party: Optional[List[RelatedParty]] = Field(alias="relatedParty", default=None)
    resource_characteristic: Optional[List[Characteristic]] = Field(alias="resourceCharacteristic", default=None)
    resource_relationship: Optional[List[ResourceRelationship]] = Field(alias="resourceRelationship", default=None)
    resource_specification: Optional[ResourceSpecificationRef] = Field(alias="resourceSpecification", default=None)
    resource_status: Optional[ResourceStatusType] = Field(alias="resourceStatus", default=None)
    usage_state: Optional[ResourceUsageStateType] = Field(alias="usageState", default=None)
    base_type: Optional[str] = Field(alias="@baseType", default=None)
    schema_location: Optional[AnyUrl] = Field(alias="@schemaLocation", default=None)
    type: Optional[str] = Field(alias="@type", default=None)

ResourceUpdate.update_forward_refs()
