# coding: utf-8

from __future__ import annotations
from typing import List, Optional

from pydantic import BaseModel, Field

class Nssai(BaseModel):
    """Nssai model"""
    sst: Optional[int] = Field(alias="sst", default=None)
    sd: Optional[int] = Field(alias="sd", default=None)

class Pdn(BaseModel):
    """Pdn model"""
    access_point_name: Optional[str] = Field(alias="access_point_name", default=None)
    nssai: Optional[List[Nssai]] = Field(alias="nssai", default=None)

class UeDbEntry(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UeDbEntry - a model defined in OpenAPI

        sim_algo: The sim_algo of this UeDbEntry [Optional].
        imsi: The imsi of this UeDbEntry [Optional].
        opc: The opc of this UeDbEntry [Optional].
        amf: The amf of this UeDbEntry [Optional].
        sqn: The sqn of this UeDbEntry [Optional].
        K: The K of this UeDbEntry [Optional].
        pdn_list: The pdn_list of this UeDbEntry [Optional].
        impi: The impi of this UeDbEntry [Optional].
        impu: The impu of this UeDbEntry [Optional].
    """

    sim_algo: Optional[str] = Field(alias="sim_algo", default=None)
    imsi: Optional[str] = Field(alias="imsi", default=None)
    opc: Optional[str] = Field(alias="opc", default=None)
    amf: Optional[int] = Field(alias="amf", default=None)
    sqn: Optional[str] = Field(alias="sqn", default=None)
    k: Optional[str] = Field(alias="K", default=None)
    pdn_list: Optional[List[Pdn]] = Field(alias="pdn_list", default=None)
    impi: Optional[str] = Field(alias="impi", default=None)
    impu: Optional[List[str]] = Field(alias="impu", default=None)
    allowed_tac: Optional[List[int]] = Field(alias="allowed_tac", default=None)
    not_allowed_tac: Optional[List[int]] = Field(alias="not_allowed_tac", default=None)

UeDbEntry.model_rebuild()
